### ISSUE TITLE
Negative functional flow values coming up a "null" instead of 0

### ISSUE THREAD

**Issue by kklausmeyer** [tnc-ca-geo/rivers-stream#56]
A user reported a bug in our API and I think the problem is coming from the input data from Ted, but I hope it is an easy fix on our end.  BAsically, it looks like some of the FFM values were very small and slightly negative.  These should have been rounded to 0, but when users request these data via the API, they are getting nulls.  Here is an example API call that returns nulls for the P10 values:

https://flow-api.codefornature.org/v2/ffm/?comids=20348831&ffms=ds_mag_50

Here is a screenshot of the raw data we got from Ted for that another COMID that shows the negative problem:
![image](https://user-images.githubusercontent.com/11560493/95640149-3a7f1300-0a50-11eb-99fd-817f0c1f835b.png)

Falk, can you look into this issue?  There shouldn't be any negative values in the FFM database, especially in the magnitude metrics.  Maybe a find and replace for all null or negative values and replace with 0?

**Comment by kklausmeyer** [comment]
Should we archive a version with the negative flow values as V1.0.0 and then have a V1.0.1 with the negative flow values fixed?

**Comment by postfalk** [comment]
@kklausmeyer  I think that is fixed. Please review and close

**Comment by postfalk** [comment]
Make sure the observed values are there too.

**Comment by kklausmeyer** [comment]
Hi Falk-  I'm still getting null values in the p10 column of the csv when I download these data from the api:
https://flow-api.codefornature.org/v2/ffm/?comids=20348831&ffms=ds_mag_50
https://flow-api.codefornature.org/v2/ffm/?comids=20348795&ffms=ds_mag_50

Can you double check to make sure I'm calling the correct version of the data?

**Comment by postfalk** [comment]
Ok. I just got mixed up with my own data versions. Consider that fixed but please check again.

**Comment by kklausmeyer** [comment]
Checked and it looks good- thank you!
